/**
 * CDDAL AST serializer — emits canonical text from a parsed Document.
 *
 * This is the AST-level analog of Ruby's per-node `to_cddal` methods
 * (lib/cdd/cddal/ast.rb). The full Database-backed Serializer
 * (lib/cdd/cddal/serializer.rb) iterates entity instances and will be
 * ported with the Database layer in Phase 3.6 — its value-formatting
 * rules are intentionally identical to the ones here so output stays
 * stable across both emission paths.
 */

import type {
  AliasDecl,
  Declaration,
  Document,
  ImportDecl,
  InstanceDecl,
  MetaClassDecl,
  PropertyAssignment,
  ValueNode,
} from "./AST";
import {
  isAliasDecl,
  isImportDecl,
  isInstanceDecl,
  isMetaClassDecl,
} from "./AST";

const HEADER = "# Generated by opencdd CDDAL serializer";

export function astToCddal(document: Document): string {
  const lines: string[] = [HEADER];
  for (const decl of document.declarations) {
    lines.push("");
    lines.push(...emitDeclaration(decl));
  }
  return lines.join("\n") + "\n";
}

function emitDeclaration(decl: Declaration): string[] {
  if (isMetaClassDecl(decl)) return emitMetaClassDecl(decl);
  if (isInstanceDecl(decl)) return emitInstanceDecl(decl);
  if (isAliasDecl(decl)) return emitAliasDecl(decl);
  if (isImportDecl(decl)) return emitImportDecl(decl);
  return [];
}

function emitMetaClassDecl(decl: MetaClassDecl): string[] {
  if (decl.propertyIdentifiers.length === 0) {
    return [`meta-class ${decl.irdi}`];
  }
  const lines = [`meta-class ${decl.irdi} {`];
  for (const id of decl.propertyIdentifiers) {
    lines.push(`  ${id}`);
  }
  lines.push("}");
  return lines;
}

function emitInstanceDecl(decl: InstanceDecl): string[] {
  const name = decl.name ?? "";
  const head = name
    ? `instance ${name} < ${decl.metaClassRef} {`
    : `instance < ${decl.metaClassRef} {`;
  const lines = [head];
  for (const assignment of decl.assignments) {
    lines.push(`  ${emitAssignment(assignment)}`);
  }
  lines.push("}");
  return lines;
}

function emitAssignment(assignment: PropertyAssignment): string {
  const key = assignment.languageTag
    ? `${assignment.identifier}.${assignment.languageTag}`
    : assignment.identifier;
  return `${key}: ${emitValue(assignment.value)}`;
}

function emitAliasDecl(decl: AliasDecl): string[] {
  return [`alias ${decl.aliasName}: ${decl.propertyId}`];
}

function emitImportDecl(decl: ImportDecl): string[] {
  if (decl.kind === "selective") {
    const names = decl.importedNames
      .map((n) =>
        n.localName === n.name ? n.name : `${n.name} as ${n.localName}`,
      )
      .join(", ");
    return [`from ${quoteString(decl.specifier)} import { ${names} }`];
  }
  if (decl.kind === "qualified") {
    return [`import ${quoteString(decl.specifier)} as ${decl.qualifier}`];
  }
  return [`import ${quoteString(decl.specifier)}`];
}

export function emitValue(value: ValueNode): string {
  switch (value.node) {
    case "literal":
      return emitLiteral(value.kind, value.raw);
    case "identifier_ref":
      return value.owner ? `${value.owner}.${value.name}` : value.name;
    case "set":
      return `{ ${value.elements.map(emitValue).join(", ")} }`;
    case "tuple":
      return `(${value.elements.map(emitValue).join(", ")})`;
    case "class_reference":
      return `${value.typeName}(${emitValue(value.argument)})`;
    case "condition":
      return `${value.left} ${value.operator} ${emitValue(value.right)}`;
  }
}

function emitLiteral(kind: string, raw: string): string {
  if (kind === "string") return quoteString(raw);
  return raw;
}

export function quoteString(s: string): string {
  const escaped = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}
