// AUTO-GENERATED by `rake generate_ts`. Do not edit by hand.
// Source: Cdd::PropertyIds::REGISTRY in lib/cdd/property_ids.rb

export type AppliesTo =
  "all" | "class" | "property" | "relation" | "value_list" | "view_control";
export type ValueKind =
  | "class_ref"
  | "condition"
  | "date"
  | "date_time"
  | "identifier_ref"
  | "set_of_refs"
  | "string";

export interface PropertyEntry {
  readonly id: string;
  readonly aliases: readonly string[];
  readonly appliesTo: AppliesTo;
  readonly multilingual: boolean;
  readonly valueKind: ValueKind;
}

export const REGISTRY: Readonly<Record<string, PropertyEntry>> = {
  MDC_P001: {
    id: "MDC_P001",
    aliases: ["code_generic"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_1: {
    id: "MDC_P001_1",
    aliases: ["code_dictionary"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_2: {
    id: "MDC_P001_2",
    aliases: ["code_supplier"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_5: {
    id: "MDC_P001_5",
    aliases: ["code"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_6: {
    id: "MDC_P001_6",
    aliases: ["code_property"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_7: {
    id: "MDC_P001_7",
    aliases: ["code_datatype"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_8: {
    id: "MDC_P001_8",
    aliases: ["code_document"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_10: {
    id: "MDC_P001_10",
    aliases: ["code_unit"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_11: {
    id: "MDC_P001_11",
    aliases: ["code_value_term"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_12: {
    id: "MDC_P001_12",
    aliases: ["code_value_list"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P001_13: {
    id: "MDC_P001_13",
    aliases: ["code_relation"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  EXT_P001: {
    id: "EXT_P001",
    aliases: ["code_view_control"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P002_1: {
    id: "MDC_P002_1",
    aliases: ["version"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P002_2: {
    id: "MDC_P002_2",
    aliases: ["revision"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P003_1: {
    id: "MDC_P003_1",
    aliases: ["original_definition_date"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "date",
  },
  MDC_P003_2: {
    id: "MDC_P003_2",
    aliases: ["current_version_date"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "date",
  },
  MDC_P003_3: {
    id: "MDC_P003_3",
    aliases: ["current_revision_date"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "date",
  },
  MDC_P004: {
    id: "MDC_P004",
    aliases: ["preferred_name"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P004_1: {
    id: "MDC_P004_1",
    aliases: ["preferred_name_localized"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P004_2: {
    id: "MDC_P004_2",
    aliases: ["synonymous_names"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P004_3: {
    id: "MDC_P004_3",
    aliases: ["short_name_localized"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P004_4: {
    id: "MDC_P004_4",
    aliases: ["name_icon"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P005: {
    id: "MDC_P005",
    aliases: ["short_name"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P005_1: {
    id: "MDC_P005_1",
    aliases: ["short_name_variant"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P006: {
    id: "MDC_P006",
    aliases: ["definition"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P006_1: {
    id: "MDC_P006_1",
    aliases: ["source_document_of_definition"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P007: {
    id: "MDC_P007",
    aliases: ["synonym"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P007_1: {
    id: "MDC_P007_1",
    aliases: ["note_localized"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P007_2: {
    id: "MDC_P007_2",
    aliases: ["remark_localized"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P008: {
    id: "MDC_P008",
    aliases: ["note"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P008_1: {
    id: "MDC_P008_1",
    aliases: ["simplified_drawing"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P008_2: {
    id: "MDC_P008_2",
    aliases: ["graphics"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P009: {
    id: "MDC_P009",
    aliases: ["remark"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P010: {
    id: "MDC_P010",
    aliases: ["superclass"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P010_1: {
    id: "MDC_P010_1",
    aliases: ["superclass_localized", "known_superclasses"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P011: {
    id: "MDC_P011",
    aliases: ["class_type"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P012: {
    id: "MDC_P012",
    aliases: ["supplier_class_ref"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P013: {
    id: "MDC_P013",
    aliases: ["is_case_of"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P014: {
    id: "MDC_P014",
    aliases: ["applicable_properties"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P014_1: {
    id: "MDC_P014_1",
    aliases: ["known_applicable_properties"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P014_2: {
    id: "MDC_P014_2",
    aliases: ["visible_properties"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P015: {
    id: "MDC_P015",
    aliases: ["applicable_types"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P015_1: {
    id: "MDC_P015_1",
    aliases: ["known_applicable_types"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P015_2: {
    id: "MDC_P015_2",
    aliases: ["visible_types"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P016: {
    id: "MDC_P016",
    aliases: ["sub_class_selection"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P033: {
    id: "MDC_P033",
    aliases: ["type_classification"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P040: {
    id: "MDC_P040",
    aliases: ["det_classification"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P090: {
    id: "MDC_P090",
    aliases: ["imported_properties"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P091: {
    id: "MDC_P091",
    aliases: ["imported_types"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P093: {
    id: "MDC_P093",
    aliases: ["imported_documents"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P094: {
    id: "MDC_P094",
    aliases: ["applicable_documents"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P094_1: {
    id: "MDC_P094_1",
    aliases: ["known_applicable_documents"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P094_2: {
    id: "MDC_P094_2",
    aliases: ["visible_documents"],
    appliesTo: "class",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P017: {
    id: "MDC_P017",
    aliases: ["class_value_assignment"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P018: {
    id: "MDC_P018",
    aliases: ["coded_name"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P018_1: {
    id: "MDC_P018_1",
    aliases: ["value_term_data_type"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "class_ref",
  },
  MDC_P020: {
    id: "MDC_P020",
    aliases: ["property_data_element_type", "property_det"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P021: {
    id: "MDC_P021",
    aliases: ["definition_class"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P022: {
    id: "MDC_P022",
    aliases: ["data_type"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "class_ref",
  },
  MDC_P023: {
    id: "MDC_P023",
    aliases: ["unit_structure", "unit_symbol"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P023_1: {
    id: "MDC_P023_1",
    aliases: ["unit_in_text"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P023_2: {
    id: "MDC_P023_2",
    aliases: ["unit_in_sgml"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P024: {
    id: "MDC_P024",
    aliases: ["value_format"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P025_1: {
    id: "MDC_P025_1",
    aliases: ["symbol", "preferred_symbol_text", "symbol_in_text"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P025_2: {
    id: "MDC_P025_2",
    aliases: ["preferred_symbol_sgml"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P025_3: {
    id: "MDC_P025_3",
    aliases: ["synonymous_symbol"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P026: {
    id: "MDC_P026",
    aliases: [],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P026_1: {
    id: "MDC_P026_1",
    aliases: [],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P027_1: {
    id: "MDC_P027_1",
    aliases: ["formula_text", "property_formula"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P027_2: {
    id: "MDC_P027_2",
    aliases: ["formula_sgml", "property_formula_localized"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P028: {
    id: "MDC_P028",
    aliases: ["condition"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "condition",
  },
  MDC_P030: {
    id: "MDC_P030",
    aliases: [],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P031: {
    id: "MDC_P031",
    aliases: [],
    appliesTo: "property",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P032: {
    id: "MDC_P032",
    aliases: [],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P041: {
    id: "MDC_P041",
    aliases: ["unit", "unit_irdi", "codefor_unit"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P042: {
    id: "MDC_P042",
    aliases: ["alternative_units", "codefor_alt_unit"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P043: {
    id: "MDC_P043",
    aliases: ["enumerated_terms", "term_irdis"],
    appliesTo: "value_list",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P044: {
    id: "MDC_P044",
    aliases: ["enumerated_values", "code_list"],
    appliesTo: "value_list",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P045: {
    id: "MDC_P045",
    aliases: ["selection_count"],
    appliesTo: "value_list",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P046: {
    id: "MDC_P046",
    aliases: ["list_type"],
    appliesTo: "value_list",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P068: {
    id: "MDC_P068",
    aliases: ["constraint", "property_constraint"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P096: {
    id: "MDC_P096",
    aliases: ["property_classification"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P097: {
    id: "MDC_P097",
    aliases: ["requirement"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P101: {
    id: "MDC_P101",
    aliases: ["alternate_id"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P102: {
    id: "MDC_P102",
    aliases: ["alternate_class_id"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P110: {
    id: "MDC_P110",
    aliases: ["super_property"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P111: {
    id: "MDC_P111",
    aliases: ["alternative_units_list"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P112: {
    id: "MDC_P112",
    aliases: ["description"],
    appliesTo: "all",
    multilingual: true,
    valueKind: "string",
  },
  MDC_P113: {
    id: "MDC_P113",
    aliases: ["example"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P114: {
    id: "MDC_P114",
    aliases: ["quantity"],
    appliesTo: "property",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P200: {
    id: "MDC_P200",
    aliases: ["relation_type"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P201: {
    id: "MDC_P201",
    aliases: ["domain", "domain_of_relation"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P202: {
    id: "MDC_P202",
    aliases: ["domain_of_function"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P203: {
    id: "MDC_P203",
    aliases: ["codomain", "codomain_of_function"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P204: {
    id: "MDC_P204",
    aliases: ["formula", "relation_formula"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P205: {
    id: "MDC_P205",
    aliases: ["formula_language"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P206: {
    id: "MDC_P206",
    aliases: ["external_solver"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P207: {
    id: "MDC_P207",
    aliases: ["trigger_event"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P208: {
    id: "MDC_P208",
    aliases: ["domain_element_type"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P209: {
    id: "MDC_P209",
    aliases: ["codomain_element_type"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P210: {
    id: "MDC_P210",
    aliases: ["role"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P211: {
    id: "MDC_P211",
    aliases: ["segment"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P212: {
    id: "MDC_P212",
    aliases: ["super_relation_irdi", "super_relation"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "identifier_ref",
  },
  MDC_P230: {
    id: "MDC_P230",
    aliases: ["applicable_relations"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  MDC_P231: {
    id: "MDC_P231",
    aliases: ["applicable_terms"],
    appliesTo: "relation",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  CIM_P001: {
    id: "CIM_P001",
    aliases: ["cim_uml_id"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  CIM_P002: {
    id: "CIM_P002",
    aliases: ["cim_package"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  CIM_P003: {
    id: "CIM_P003",
    aliases: ["cim_property_type"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  CIM_P004: {
    id: "CIM_P004",
    aliases: ["cim_basic_datatype"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  CIM_P005: {
    id: "CIM_P005",
    aliases: ["cim_multiplicity"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P066: {
    id: "MDC_P066",
    aliases: ["data_object_identifier"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "string",
  },
  MDC_P067: {
    id: "MDC_P067",
    aliases: ["time_stamp"],
    appliesTo: "all",
    multilingual: false,
    valueKind: "date_time",
  },
  EXT_P002: {
    id: "EXT_P002",
    aliases: ["controlled_classes"],
    appliesTo: "view_control",
    multilingual: false,
    valueKind: "set_of_refs",
  },
  EXT_P003: {
    id: "EXT_P003",
    aliases: ["shown_properties"],
    appliesTo: "view_control",
    multilingual: false,
    valueKind: "set_of_refs",
  },
};

export const MDC_P001 = "MDC_P001";
export const MDC_P001_1 = "MDC_P001_1";
export const MDC_P001_2 = "MDC_P001_2";
export const MDC_P001_5 = "MDC_P001_5";
export const MDC_P001_6 = "MDC_P001_6";
export const MDC_P001_7 = "MDC_P001_7";
export const MDC_P001_8 = "MDC_P001_8";
export const MDC_P001_10 = "MDC_P001_10";
export const MDC_P001_11 = "MDC_P001_11";
export const MDC_P001_12 = "MDC_P001_12";
export const MDC_P001_13 = "MDC_P001_13";
export const EXT_P001 = "EXT_P001";
export const MDC_P002_1 = "MDC_P002_1";
export const MDC_P002_2 = "MDC_P002_2";
export const MDC_P003_1 = "MDC_P003_1";
export const MDC_P003_2 = "MDC_P003_2";
export const MDC_P003_3 = "MDC_P003_3";
export const MDC_P004 = "MDC_P004";
export const MDC_P004_1 = "MDC_P004_1";
export const MDC_P004_2 = "MDC_P004_2";
export const MDC_P004_3 = "MDC_P004_3";
export const MDC_P004_4 = "MDC_P004_4";
export const MDC_P005 = "MDC_P005";
export const MDC_P005_1 = "MDC_P005_1";
export const MDC_P006 = "MDC_P006";
export const MDC_P006_1 = "MDC_P006_1";
export const MDC_P007 = "MDC_P007";
export const MDC_P007_1 = "MDC_P007_1";
export const MDC_P007_2 = "MDC_P007_2";
export const MDC_P008 = "MDC_P008";
export const MDC_P008_1 = "MDC_P008_1";
export const MDC_P008_2 = "MDC_P008_2";
export const MDC_P009 = "MDC_P009";
export const MDC_P010 = "MDC_P010";
export const MDC_P010_1 = "MDC_P010_1";
export const MDC_P011 = "MDC_P011";
export const MDC_P012 = "MDC_P012";
export const MDC_P013 = "MDC_P013";
export const MDC_P014 = "MDC_P014";
export const MDC_P014_1 = "MDC_P014_1";
export const MDC_P014_2 = "MDC_P014_2";
export const MDC_P015 = "MDC_P015";
export const MDC_P015_1 = "MDC_P015_1";
export const MDC_P015_2 = "MDC_P015_2";
export const MDC_P016 = "MDC_P016";
export const MDC_P033 = "MDC_P033";
export const MDC_P040 = "MDC_P040";
export const MDC_P090 = "MDC_P090";
export const MDC_P091 = "MDC_P091";
export const MDC_P093 = "MDC_P093";
export const MDC_P094 = "MDC_P094";
export const MDC_P094_1 = "MDC_P094_1";
export const MDC_P094_2 = "MDC_P094_2";
export const MDC_P017 = "MDC_P017";
export const MDC_P018 = "MDC_P018";
export const MDC_P018_1 = "MDC_P018_1";
export const MDC_P020 = "MDC_P020";
export const MDC_P021 = "MDC_P021";
export const MDC_P022 = "MDC_P022";
export const MDC_P023 = "MDC_P023";
export const MDC_P023_1 = "MDC_P023_1";
export const MDC_P023_2 = "MDC_P023_2";
export const MDC_P024 = "MDC_P024";
export const MDC_P025_1 = "MDC_P025_1";
export const MDC_P025_2 = "MDC_P025_2";
export const MDC_P025_3 = "MDC_P025_3";
export const MDC_P026 = "MDC_P026";
export const MDC_P026_1 = "MDC_P026_1";
export const MDC_P027_1 = "MDC_P027_1";
export const MDC_P027_2 = "MDC_P027_2";
export const MDC_P028 = "MDC_P028";
export const MDC_P030 = "MDC_P030";
export const MDC_P031 = "MDC_P031";
export const MDC_P032 = "MDC_P032";
export const MDC_P041 = "MDC_P041";
export const MDC_P042 = "MDC_P042";
export const MDC_P043 = "MDC_P043";
export const MDC_P044 = "MDC_P044";
export const MDC_P045 = "MDC_P045";
export const MDC_P046 = "MDC_P046";
export const MDC_P068 = "MDC_P068";
export const MDC_P096 = "MDC_P096";
export const MDC_P097 = "MDC_P097";
export const MDC_P101 = "MDC_P101";
export const MDC_P102 = "MDC_P102";
export const MDC_P110 = "MDC_P110";
export const MDC_P111 = "MDC_P111";
export const MDC_P112 = "MDC_P112";
export const MDC_P113 = "MDC_P113";
export const MDC_P114 = "MDC_P114";
export const MDC_P200 = "MDC_P200";
export const MDC_P201 = "MDC_P201";
export const MDC_P202 = "MDC_P202";
export const MDC_P203 = "MDC_P203";
export const MDC_P204 = "MDC_P204";
export const MDC_P205 = "MDC_P205";
export const MDC_P206 = "MDC_P206";
export const MDC_P207 = "MDC_P207";
export const MDC_P208 = "MDC_P208";
export const MDC_P209 = "MDC_P209";
export const MDC_P210 = "MDC_P210";
export const MDC_P211 = "MDC_P211";
export const MDC_P212 = "MDC_P212";
export const MDC_P230 = "MDC_P230";
export const MDC_P231 = "MDC_P231";
export const CIM_P001 = "CIM_P001";
export const CIM_P002 = "CIM_P002";
export const CIM_P003 = "CIM_P003";
export const CIM_P004 = "CIM_P004";
export const CIM_P005 = "CIM_P005";
export const MDC_P066 = "MDC_P066";
export const MDC_P067 = "MDC_P067";
export const EXT_P002 = "EXT_P002";
export const EXT_P003 = "EXT_P003";

export function entry(id: string): PropertyEntry | undefined {
  return REGISTRY[id];
}

export function multilingual(id: string): boolean {
  return REGISTRY[id]?.multilingual ?? false;
}

export function appliesTo(id: string): AppliesTo | undefined {
  return REGISTRY[id]?.appliesTo;
}

export function valueKind(id: string): ValueKind | undefined {
  return REGISTRY[id]?.valueKind;
}

export const ALL_IDS: readonly string[] = Object.keys(REGISTRY);

export function canonicalId(name: string): string | undefined {
  if (name in REGISTRY) return name;
  return ALIAS_MAP[name];
}

export function normalize(rawId: string | null | undefined): string | null {
  if (!rawId) return null;
  const s = rawId.trim();
  if (!s) return null;
  const match = s.match(/\.([A-Za-z0-9-]+)$/);
  if (!match) return canonicalId(s) ?? s;
  const base = s.slice(0, s.length - match[0].length);
  const lang = match[1];
  const canonical = canonicalId(base) ?? base;
  return `${canonical}.${lang}`;
}

const ALIAS_MAP: Readonly<Record<string, string>> = {
  code_generic: "MDC_P001",
  code_dictionary: "MDC_P001_1",
  code_supplier: "MDC_P001_2",
  code: "MDC_P001_5",
  code_property: "MDC_P001_6",
  code_datatype: "MDC_P001_7",
  code_document: "MDC_P001_8",
  code_unit: "MDC_P001_10",
  code_value_term: "MDC_P001_11",
  code_value_list: "MDC_P001_12",
  code_relation: "MDC_P001_13",
  code_view_control: "EXT_P001",
  version: "MDC_P002_1",
  revision: "MDC_P002_2",
  original_definition_date: "MDC_P003_1",
  current_version_date: "MDC_P003_2",
  current_revision_date: "MDC_P003_3",
  preferred_name: "MDC_P004",
  preferred_name_localized: "MDC_P004_1",
  synonymous_names: "MDC_P004_2",
  short_name_localized: "MDC_P004_3",
  name_icon: "MDC_P004_4",
  short_name: "MDC_P005",
  short_name_variant: "MDC_P005_1",
  definition: "MDC_P006",
  source_document_of_definition: "MDC_P006_1",
  synonym: "MDC_P007",
  note_localized: "MDC_P007_1",
  remark_localized: "MDC_P007_2",
  note: "MDC_P008",
  simplified_drawing: "MDC_P008_1",
  graphics: "MDC_P008_2",
  remark: "MDC_P009",
  superclass: "MDC_P010",
  superclass_localized: "MDC_P010_1",
  known_superclasses: "MDC_P010_1",
  class_type: "MDC_P011",
  supplier_class_ref: "MDC_P012",
  is_case_of: "MDC_P013",
  applicable_properties: "MDC_P014",
  known_applicable_properties: "MDC_P014_1",
  visible_properties: "MDC_P014_2",
  applicable_types: "MDC_P015",
  known_applicable_types: "MDC_P015_1",
  visible_types: "MDC_P015_2",
  sub_class_selection: "MDC_P016",
  type_classification: "MDC_P033",
  det_classification: "MDC_P040",
  imported_properties: "MDC_P090",
  imported_types: "MDC_P091",
  imported_documents: "MDC_P093",
  applicable_documents: "MDC_P094",
  known_applicable_documents: "MDC_P094_1",
  visible_documents: "MDC_P094_2",
  class_value_assignment: "MDC_P017",
  coded_name: "MDC_P018",
  value_term_data_type: "MDC_P018_1",
  property_data_element_type: "MDC_P020",
  property_det: "MDC_P020",
  definition_class: "MDC_P021",
  data_type: "MDC_P022",
  unit_structure: "MDC_P023",
  unit_symbol: "MDC_P023",
  unit_in_text: "MDC_P023_1",
  unit_in_sgml: "MDC_P023_2",
  value_format: "MDC_P024",
  symbol: "MDC_P025_1",
  preferred_symbol_text: "MDC_P025_1",
  symbol_in_text: "MDC_P025_1",
  preferred_symbol_sgml: "MDC_P025_2",
  synonymous_symbol: "MDC_P025_3",
  formula_text: "MDC_P027_1",
  property_formula: "MDC_P027_1",
  formula_sgml: "MDC_P027_2",
  property_formula_localized: "MDC_P027_2",
  condition: "MDC_P028",
  unit: "MDC_P041",
  unit_irdi: "MDC_P041",
  codefor_unit: "MDC_P041",
  alternative_units: "MDC_P042",
  codefor_alt_unit: "MDC_P042",
  enumerated_terms: "MDC_P043",
  term_irdis: "MDC_P043",
  enumerated_values: "MDC_P044",
  code_list: "MDC_P044",
  selection_count: "MDC_P045",
  list_type: "MDC_P046",
  constraint: "MDC_P068",
  property_constraint: "MDC_P068",
  property_classification: "MDC_P096",
  requirement: "MDC_P097",
  alternate_id: "MDC_P101",
  alternate_class_id: "MDC_P102",
  super_property: "MDC_P110",
  alternative_units_list: "MDC_P111",
  description: "MDC_P112",
  example: "MDC_P113",
  quantity: "MDC_P114",
  relation_type: "MDC_P200",
  domain: "MDC_P201",
  domain_of_relation: "MDC_P201",
  domain_of_function: "MDC_P202",
  codomain: "MDC_P203",
  codomain_of_function: "MDC_P203",
  formula: "MDC_P204",
  relation_formula: "MDC_P204",
  formula_language: "MDC_P205",
  external_solver: "MDC_P206",
  trigger_event: "MDC_P207",
  domain_element_type: "MDC_P208",
  codomain_element_type: "MDC_P209",
  role: "MDC_P210",
  segment: "MDC_P211",
  super_relation_irdi: "MDC_P212",
  super_relation: "MDC_P212",
  applicable_relations: "MDC_P230",
  applicable_terms: "MDC_P231",
  cim_uml_id: "CIM_P001",
  cim_package: "CIM_P002",
  cim_property_type: "CIM_P003",
  cim_basic_datatype: "CIM_P004",
  cim_multiplicity: "CIM_P005",
  data_object_identifier: "MDC_P066",
  time_stamp: "MDC_P067",
  controlled_classes: "EXT_P002",
  shown_properties: "EXT_P003",
};
